### ISSUE TITLE
[FEATURE REQ] View active tab

### ISSUE THREAD

**Issue by assenzostefano** [browser-history/browser-history#202]
**Is your feature request related to a problem? Please describe.**
I am creating a small project to practice Python, in practice if we visit YouTube (or other sites) it automatically turns off the PC (it serves to not distract people while they are working).

**Describe the solution you'd like**
It would be useful to add to the library the possibility to write the currently active tabs (of the various browsers) with the link of the site they are visiting in a file (example: .txt, csv etc. ..) in an orderly manner.

**Comment by Samyak2** [comment]
Thank you for the suggestion.

Although, I don't think this is appropriate for this project. `browser-history` queries the databases of browsers to get history, bookmarks, etc. This usually only works when the browser is inactive (closed). Getting the list of active tabs is a whole another problem, not intended to be solved by this package.

I think this is more appropriate for a browser extension (usually written in JS) than a standalone python app.

Here are a few links that may be helpful:
https://superuser.com/a/1310873
https://stackoverflow.com/a/7537994

**Comment by assenzostefano** [comment]
Thanks a lot, I guess I'll have to learn JS.
