### ISSUE TITLE
[BUG] CI failing for ubuntu + python3.6

### ISSUE THREAD

**Issue by ObaraEmmanuel** [browser-history/browser-history#240]
**Describe the bug**
CI is failing for python3.6 on `ubuntu-latest`. This is because `ubuntu-latest` now uses ubuntu-22.04. This is somehow breaking the setting up of python3.6 which doesn't appear to be properly supported anymore. @Samyak2 should we revert to `ubuntu-20.04` or remove support for python3.6 altogether?

**Comment by Samyak2** [comment]
IMO we should drop 3.6 since it has reached end-of-life. We should add 3.10 and 3.11 though.
